// <auto-generated />

using UnityEngine;
using UnityEngine.Scripting;

namespace HBP.Data.Tools
{
    [Preserve]
    public static class GeneratedDataSerializationTypes
    {
        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterAssembliesLoaded)]
        public static void Register()
        {
            global::HBP.Core.Tools.SerializationTypeRegistry.RegisterGenerated(typeof(global::HBP.Data.BIDS.AnatomicalDataRule), "HBP.Data.BIDS.AnatomicalDataRule");
            global::HBP.Core.Tools.SerializationTypeRegistry.RegisterGenerated(typeof(global::HBP.Data.BIDS.BIDSExportConfiguration), "HBP.Data.BIDS.BIDSExportConfiguration");
            global::HBP.Core.Tools.SerializationTypeRegistry.RegisterGenerated(typeof(global::HBP.Data.BIDS.CoordinateSystemRule), "HBP.Data.BIDS.CoordinateSystemRule");
            global::HBP.Core.Tools.SerializationTypeRegistry.RegisterGenerated(typeof(global::HBP.Data.BIDS.CoordSystemFile), "HBP.Data.BIDS.CoordSystemFile");
            global::HBP.Core.Tools.SerializationTypeRegistry.RegisterGenerated(typeof(global::HBP.Data.BIDS.DatasetDescriptionFile), "HBP.Data.BIDS.DatasetDescriptionFile");
            global::HBP.Core.Tools.SerializationTypeRegistry.RegisterGenerated(typeof(global::HBP.Data.BIDS.GeneratedByField), "HBP.Data.BIDS.GeneratedByField");
            global::HBP.Core.Tools.SerializationTypeRegistry.RegisterGenerated(typeof(global::HBP.Data.BIDS.TaskFile), "HBP.Data.BIDS.TaskFile");
            global::HBP.Core.Tools.SerializationTypeRegistry.RegisterGenerated(typeof(global::HBP.Data.Informations.CCEPData), "HBP.Data.Informations.CCEPData");
            global::HBP.Core.Tools.SerializationTypeRegistry.RegisterGenerated(typeof(global::HBP.Data.Informations.ChannelStruct), "HBP.Data.Informations.ChannelStruct");
            global::HBP.Core.Tools.SerializationTypeRegistry.RegisterGenerated(typeof(global::HBP.Data.Informations.ChannelStructsGroup), "HBP.Data.Informations.ChannelStructsGroup");
            global::HBP.Core.Tools.SerializationTypeRegistry.RegisterGenerated(typeof(global::HBP.Data.Informations.Column), "HBP.Data.Informations.Column");
            global::HBP.Core.Tools.SerializationTypeRegistry.RegisterGenerated(typeof(global::HBP.Data.Informations.Data), "HBP.Data.Informations.Data");
            global::HBP.Core.Tools.SerializationTypeRegistry.RegisterGenerated(typeof(global::HBP.Data.Informations.IEEGData), "HBP.Data.Informations.IEEGData");
            global::HBP.Core.Tools.SerializationTypeRegistry.RegisterGenerated(typeof(global::HBP.Data.Informations.MEGData), "HBP.Data.Informations.MEGData");
            global::HBP.Core.Tools.SerializationTypeRegistry.RegisterGenerated(typeof(global::HBP.Data.Informations.SceneData), "HBP.Data.Informations.SceneData");
        }
    }
}
