#!/usr/bin/env python3
"""Generate deterministic native-format fixtures for HiBoP tests.

The script intentionally does not generate Micromed TRC or Elan EEG/POS/ENT
files. It creates two extra BrainVision recordings that can be converted
manually to those proprietary/internal formats and copied back into the output
folder later.
"""

from __future__ import annotations

import argparse
import json
import math
import shutil
from pathlib import Path

import numpy as np

REQUIREMENTS_PATH = (
    "Assets/Tests/EditMode/HBP.Serialization.Tests/native_fixture_requirements.txt"
)

try:
    import nibabel as nib
    import mne
    import pyedflib
except ImportError as exc:
    raise SystemExit(
        "Missing dependency. Install with:\n"
        f"  python -m pip install -r {REQUIREMENTS_PATH}"
    ) from exc


CHANNELS = ("A1", "A2", "A3")
SAMPLE_RATE = 200.0
N_SAMPLES = 400
EVENTS = (
    {"sample": 50, "code": 11, "label": "Stimulus/S 11"},
    {"sample": 160, "code": 12, "label": "Stimulus/S 12"},
    {"sample": 260, "code": 21, "label": "Response/R 21"},
)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        default="Assets/Tests/Fixtures/Native",
        help="Output folder, relative to the repository root by default.",
    )
    parser.add_argument(
        "--clean",
        action="store_true",
        help="Delete the output folder before generating fixtures.",
    )
    args = parser.parse_args()

    repo_root = find_repository_root(Path(__file__).resolve())
    output = Path(args.output)
    if not output.is_absolute():
        output = repo_root / output

    if args.clean and output.exists():
        shutil.rmtree(output)
    output.mkdir(parents=True, exist_ok=True)

    signal = make_signal()
    manifest: dict[str, object] = {
        "description": "Deterministic synthetic native fixtures for HiBoP tests.",
        "sample_rate_hz": SAMPLE_RATE,
        "channels": list(CHANNELS),
        "events": EVENTS,
        "paths": {},
    }

    paths: dict[str, object] = manifest["paths"]  # type: ignore[assignment]
    paths["brainvision"] = generate_brainvision_fixtures(output / "EEG" / "BrainVision", signal)
    paths["manual_conversion_targets"] = generate_manual_conversion_targets(output / "EEG")
    paths["edf"] = generate_edf_fixture(output / "EEG" / "EDF", signal)
    paths["fif"] = generate_fif_fixture(output / "EEG" / "FIF", signal)
    paths["csv"] = generate_csv_fixture(output / "Static")
    paths["nifti"] = generate_nifti_fixtures(output / "Nifti")
    paths["meshes"] = generate_mesh_fixtures(output / "Meshes")
    paths["patient_tree"] = generate_patient_tree(output / "Patients" / "synthetic-patient")
    paths["localizers"] = generate_localizer_tree(output / "Localizers")
    paths["bids"] = generate_bids_tree(output / "BIDS", signal)

    manifest_path = output / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    (output / "README.md").write_text(
        "# HiBoP Native Test Fixtures\n\n"
        "Generated by "
        "`Assets/Tests/EditMode/HBP.Serialization.Tests/generate_native_test_fixtures.py`.\n\n"
        "The script intentionally skips Micromed `.trc` and Elan files. Convert\n"
        "`EEG/BrainVision/conversion_seed_trc.*` and\n"
        "`EEG/BrainVision/conversion_seed_elan.*` manually, then place the\n"
        "converted files in `EEG/Micromed/` and `EEG/Elan/`.\n",
        encoding="utf-8",
    )
    print(f"Generated native fixtures in {output}")


def find_repository_root(start: Path) -> Path:
    for candidate in (start, *start.parents):
        if (candidate / "Assets").is_dir() and (candidate / "ProjectSettings").is_dir():
            return candidate
    raise RuntimeError(f"Could not find Unity repository root from {start}")


def make_signal() -> np.ndarray:
    times = np.arange(N_SAMPLES, dtype=np.float64) / SAMPLE_RATE
    signal = np.vstack(
        [
            20.0 * np.sin(2.0 * math.pi * 8.0 * times),
            10.0 * np.cos(2.0 * math.pi * 4.0 * times) + 0.1 * np.arange(N_SAMPLES),
            np.linspace(-5.0, 5.0, N_SAMPLES),
        ]
    )
    return signal.astype(np.float32)


def generate_brainvision_fixtures(folder: Path, signal: np.ndarray) -> list[str]:
    folder.mkdir(parents=True, exist_ok=True)
    bases = [
        "native_brainvision_alpha",
        "native_brainvision_beta",
        "conversion_seed_trc",
        "conversion_seed_elan",
    ]
    generated: list[str] = []
    for index, base in enumerate(bases):
        scaled = signal + index
        write_brainvision(folder, base, scaled)
        generated.append(relative(folder / f"{base}.vhdr"))
    return generated


def write_brainvision(folder: Path, base: str, signal: np.ndarray) -> None:
    eeg_name = f"{base}.eeg"
    vmrk_name = f"{base}.vmrk"
    vhdr_name = f"{base}.vhdr"

    multiplexed = signal.T.astype("<f4").ravel()
    (folder / eeg_name).write_bytes(multiplexed.tobytes())

    sampling_interval_us = 1_000_000.0 / SAMPLE_RATE
    channel_infos = "\n".join(
        f"Ch{idx}={name},,1,uV" for idx, name in enumerate(CHANNELS, start=1)
    )
    (folder / vhdr_name).write_text(
        "Brain Vision Data Exchange Header File Version 1.0\n"
        "[Common Infos]\n"
        f"DataFile={eeg_name}\n"
        f"MarkerFile={vmrk_name}\n"
        "DataFormat=BINARY\n"
        "DataOrientation=MULTIPLEXED\n"
        f"NumberOfChannels={len(CHANNELS)}\n"
        f"SamplingInterval={sampling_interval_us:.5f}\n"
        "\n"
        "[Binary Infos]\n"
        "BinaryFormat=IEEE_FLOAT_32\n"
        "\n"
        "[Channel Infos]\n"
        f"{channel_infos}\n",
        encoding="utf-8",
    )

    marker_lines = ["Mk1=New Segment,,1,1,0,00000000000000000000"]
    for marker_index, event in enumerate(EVENTS, start=2):
        marker_lines.append(
            f"Mk{marker_index}=Stimulus,S {event['code']},{event['sample']},1,0"
        )
    (folder / vmrk_name).write_text(
        "Brain Vision Data Exchange Marker File, Version 1.0\n"
        "[Common Infos]\n"
        f"DataFile={eeg_name}\n"
        "\n"
        "[Marker Infos]\n"
        + "\n".join(marker_lines)
        + "\n",
        encoding="utf-8",
    )


def generate_edf_fixture(folder: Path, signal: np.ndarray) -> str:
    folder.mkdir(parents=True, exist_ok=True)
    path = folder / "native_edf.edf"
    writer = pyedflib.EdfWriter(str(path), len(CHANNELS), file_type=pyedflib.FILETYPE_EDFPLUS)
    headers = []
    for channel in CHANNELS:
        headers.append(
            {
                "label": channel,
                "dimension": "uV",
                "sample_frequency": SAMPLE_RATE,
                "physical_min": -100.0,
                "physical_max": 100.0,
                "digital_min": -32768,
                "digital_max": 32767,
                "transducer": "synthetic",
                "prefilter": "none",
            }
        )
    try:
        writer.setSignalHeaders(headers)
        writer.writeSamples(signal)
        for event in EVENTS:
            writer.writeAnnotation(event["sample"] / SAMPLE_RATE, 0.001, str(event["code"]))
    finally:
        writer.close()
    return relative(path)


def generate_manual_conversion_targets(folder: Path) -> dict[str, str]:
    micromed = folder / "Micromed"
    elan = folder / "Elan"
    micromed.mkdir(parents=True, exist_ok=True)
    elan.mkdir(parents=True, exist_ok=True)
    (micromed / "README.md").write_text(
        "Convert `../BrainVision/conversion_seed_trc.vhdr` with the internal C++ tool\n"
        "and save the result here as `native_from_brainvision.trc`.\n",
        encoding="utf-8",
    )
    (elan / "README.md").write_text(
        "Convert `../BrainVision/conversion_seed_elan.vhdr` with the internal C++ tool\n"
        "and save the result here as `native_from_brainvision.eeg` plus the associated\n"
        "`native_from_brainvision.eeg.ent`, `.pos` and optional `.txt` files.\n",
        encoding="utf-8",
    )
    return {
        "micromed_trc": relative(micromed / "native_from_brainvision.trc"),
        "elan_eeg": relative(elan / "native_from_brainvision.eeg"),
        "elan_header": relative(elan / "native_from_brainvision.eeg.ent"),
        "elan_pos": relative(elan / "native_from_brainvision.pos"),
        "elan_notes": relative(elan / "native_from_brainvision.txt"),
    }


def generate_fif_fixture(folder: Path, signal: np.ndarray) -> str:
    folder.mkdir(parents=True, exist_ok=True)
    path = folder / "native_raw.fif"
    info = mne.create_info(list(CHANNELS), sfreq=SAMPLE_RATE, ch_types="eeg")
    raw = mne.io.RawArray(signal * 1e-6, info, verbose=False)
    annotations = mne.Annotations(
        onset=[event["sample"] / SAMPLE_RATE for event in EVENTS],
        duration=[0.001 for _ in EVENTS],
        description=[str(event["code"]) for event in EVENTS],
    )
    raw.set_annotations(annotations)
    raw.save(path, overwrite=True, verbose=False)
    return relative(path)


def generate_csv_fixture(folder: Path) -> str:
    folder.mkdir(parents=True, exist_ok=True)
    path = folder / "native_static.csv"
    path.write_text(
        "channel,baseline,response\n"
        "A1,0.1,1.5\n"
        "A2,0.2,2.5\n"
        "A3,0.3,3.5\n",
        encoding="utf-8",
    )
    return relative(path)


def generate_nifti_fixtures(folder: Path) -> dict[str, str]:
    folder.mkdir(parents=True, exist_ok=True)
    affine = np.eye(4, dtype=np.float32)
    grid = np.arange(125, dtype=np.float32).reshape(5, 5, 5)
    fmri_3d = folder / "fmri_3d.nii"
    fmri_4d = folder / "fmri_4d.nii.gz"
    mask = folder / "mask_binary.nii"
    mri = folder / "mri_t1.nii"
    megv_mask = folder / "megv_mask.nii"
    nib.save(nib.Nifti1Image(grid, affine), fmri_3d)
    nib.save(nib.Nifti1Image(np.stack([grid, grid + 10.0, grid + 20.0], axis=-1), affine), fmri_4d)
    nib.save(nib.Nifti1Image((grid % 3 == 0).astype(np.uint8), affine), mask)
    nib.save(nib.Nifti1Image(grid + 100.0, affine), mri)
    nib.save(nib.Nifti1Image((grid % 5 == 0).astype(np.uint8), affine), megv_mask)
    return {
        "fmri_3d": relative(fmri_3d),
        "fmri_4d": relative(fmri_4d),
        "mask_binary": relative(mask),
        "mri_t1": relative(mri),
        "megv_mask": relative(megv_mask),
    }


def generate_mesh_fixtures(folder: Path) -> dict[str, str]:
    folder.mkdir(parents=True, exist_ok=True)
    write_trm(folder / "MNI.trm")
    names = [
        "MNI_Lhemi",
        "MNI_Rhemi",
        "MNI_Lwhite",
        "MNI_Rwhite",
        "MNI_Lwhite_inflated",
        "MNI_Rwhite_inflated",
        "single_surface",
        "single_surface_marsAtlas",
    ]
    result = {"transform": relative(folder / "MNI.trm")}
    for index, name in enumerate(names):
        path = folder / f"{name}.gii"
        write_gifti_tetra(path, offset=index * 0.25)
        result[name] = relative(path)
    return result


def generate_patient_tree(folder: Path) -> dict[str, str]:
    mesh_folder = folder / "t1mri" / "T1pre_synthetic" / "default_analysis" / "segmentation" / "mesh"
    atlas_folder = mesh_folder / "surface_analysis"
    registration_folder = folder / "t1mri" / "T1pre_synthetic" / "registration"
    mri_folder = folder / "t1mri" / "T1pre_synthetic"
    mesh_folder.mkdir(parents=True, exist_ok=True)
    atlas_folder.mkdir(parents=True, exist_ok=True)
    registration_folder.mkdir(parents=True, exist_ok=True)
    write_trm(registration_folder / "RawT1-synthetic-patient_T1pre_synthetic_TO_Scanner_Based.trm")
    nib.save(nib.Nifti1Image(np.arange(64, dtype=np.float32).reshape(4, 4, 4), np.eye(4)), mri_folder / "synthetic-patient.nii")
    for name in (
        "synthetic-patient_Lhemi",
        "synthetic-patient_Rhemi",
        "synthetic-patient_Lwhite",
        "synthetic-patient_Rwhite",
    ):
        write_gifti_tetra(mesh_folder / f"{name}.gii")
    for name in (
        "synthetic-patient_Lwhite_parcels_marsAtlas",
        "synthetic-patient_Rwhite_parcels_marsAtlas",
    ):
        write_gifti_tetra(atlas_folder / f"{name}.gii")
    return {"root": relative(folder)}


def generate_localizer_tree(folder: Path) -> dict[str, str]:
    data_folder = folder / "protocol-alpha" / "signal-alpha"
    data_folder.mkdir(parents=True, exist_ok=True)
    affine = np.eye(4, dtype=np.float32)
    grid = np.arange(27, dtype=np.float32).reshape(3, 3, 3)
    files = {
        "bloc-alpha": data_folder / "bloc-alpha.nii",
        "bloc-alpha-mask": data_folder / "bloc-alpha_MASK.nii",
        "bloc-beta": data_folder / "bloc-beta.nii.gz",
        "bloc-beta-mask": data_folder / "bloc-beta_MASK.nii.gz",
    }
    nib.save(nib.Nifti1Image(grid, affine), files["bloc-alpha"])
    nib.save(nib.Nifti1Image((grid > 10).astype(np.uint8), affine), files["bloc-alpha-mask"])
    nib.save(nib.Nifti1Image(grid + 5.0, affine), files["bloc-beta"])
    nib.save(nib.Nifti1Image((grid < 20).astype(np.uint8), affine), files["bloc-beta-mask"])
    return {key: relative(value) for key, value in files.items()}


def generate_bids_tree(folder: Path, signal: np.ndarray) -> dict[str, str]:
    anat = folder / "sub-01" / "ses-pre" / "anat"
    ieeg = folder / "sub-01" / "ses-post" / "ieeg"
    anat.mkdir(parents=True, exist_ok=True)
    ieeg.mkdir(parents=True, exist_ok=True)
    t1 = anat / "sub-01_ses-pre_T1w.nii"
    nib.save(nib.Nifti1Image(np.arange(64, dtype=np.float32).reshape(4, 4, 4), np.eye(4)), t1)
    write_brainvision(ieeg, "sub-01_ses-post_task-protocol-alpha_acq-raw_ieeg", signal)
    channels_tsv = ieeg / "sub-01_ses-post_task-protocol-alpha_acq-raw_channels.tsv"
    channels_tsv.write_text(
        "name\ttype\tunits\n" + "\n".join(f"{channel}\tSEEG\tuV" for channel in CHANNELS) + "\n",
        encoding="utf-8",
    )
    sidecar = ieeg / "sub-01_ses-post_task-protocol-alpha_acq-raw_ieeg.json"
    sidecar.write_text(
        json.dumps({"TaskName": "protocol-alpha", "SamplingFrequency": SAMPLE_RATE}, indent=2),
        encoding="utf-8",
    )
    return {
        "t1w": relative(t1),
        "ieeg_header": relative(ieeg / "sub-01_ses-post_task-protocol-alpha_acq-raw_ieeg.vhdr"),
        "channels": relative(channels_tsv),
        "sidecar": relative(sidecar),
    }


def write_gifti_tetra(path: Path, offset: float = 0.0) -> None:
    points = np.array(
        [
            [0.0 + offset, 0.0, 0.0],
            [1.0 + offset, 0.0, 0.0],
            [0.0 + offset, 1.0, 0.0],
            [0.0 + offset, 0.0, 1.0],
        ],
        dtype=np.float32,
    )
    faces = np.array([[0, 1, 2], [0, 1, 3], [0, 2, 3], [1, 2, 3]], dtype=np.int32)
    image = nib.gifti.GiftiImage(
        darrays=[
            nib.gifti.GiftiDataArray(points, intent="NIFTI_INTENT_POINTSET"),
            nib.gifti.GiftiDataArray(faces, intent="NIFTI_INTENT_TRIANGLE"),
        ]
    )
    nib.save(image, path)


def write_trm(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "1 0 0 0\n"
        "0 1 0 0\n"
        "0 0 1 0\n"
        "0 0 0 1\n",
        encoding="ascii",
    )


def relative(path: Path) -> str:
    return path.as_posix()


if __name__ == "__main__":
    main()
